apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-app.fullname" . }}
  labels:
    {{- include "otus-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "otus-app.selectorLabels" . | nindent 4 }}
